example:
  property: I am the default profile
spring:
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/licensing
      username: andy
      password: password
      dbcp2:
        validation-query: select 1
        test-while-idle: true