server:
  port: 9010
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/organization
    username: andy
    password: password
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      dbcp2:
        validation-query: select 1
        test-while-idle: true
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:5555/authservice/user